name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v2.3.3
        with:
          python-version: 3.8
      
      - name: Install Poetry
        run: pip install poetry
      
      - name: Install dependencies
        run: poetry install
      
      - name: Run unit tests
        run: poetry run pytest src
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
          
      - name: Setup chromedriver
        uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          
      - name: Run robot tests
        run: bash run_robot_tests.sh
        env: 
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
          FLASK_DEBUG: 1
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Enable Codecov
        uses: codecov/codecov-action@v3.1.1
      - name: Generate coverage report
        run: poetry run coverage xml
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
      - name: Upload coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
